### ISSUE TITLE
Unable to start gerrit

### ISSUE THREAD

**Issue by mbhagavathula** [GerritCodeReview/docker-gerrit#10]
gerrit_1      | Running Gerrit Code Review:
gerrit_1      | [2018-08-15 03:53:33,484] [main] ERROR com.google.gerrit.pgm.Daemon : Unable to start daemon
gerrit_1      | com.google.gerrit.common.Die: Unable to determine SqlDialect
gerrit_1      |   caused by org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (The server requested password-based authentication, but no password was provided.)
gerrit_1      |   caused by org.postgresql.util.PSQLException: The server requested password-based authentication, but no password was provided.
gerrit_1      |         at com.google.gerrit.pgm.util.AbstractProgram.die(AbstractProgram.java:84)
gerrit_1      |         at com.google.gerrit.pgm.util.SiteProgram.createDbInjector(SiteProgram.java:217)
gerrit_1      |         at com.google.gerrit.pgm.Daemon.start(Daemon.java:325)
gerrit_1      |         at com.google.gerrit.pgm.Daemon.run(Daemon.java:256)
gerrit_1      |         at com.google.gerrit.pgm.util.AbstractProgram.main(AbstractProgram.java:61)
gerrit_1      |         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
gerrit_1      |         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
gerrit_1      |         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
gerrit_1      |         at java.lang.reflect.Method.invoke(Method.java:498)
gerrit_1      |         at com.google.gerrit.launcher.GerritLauncher.invokeProgram(GerritLauncher.java:223)
gerrit_1      |         at com.google.gerrit.launcher.GerritLauncher.mainImpl(GerritLauncher.java:119)
gerrit_1      |         at com.google.gerrit.launcher.GerritLauncher.main(GerritLauncher.java:63)
gerrit_1      |         at Main.main(Main.java:24)
gerrit_1      | Caused by: java.lang.RuntimeException: DbInjector failed
gerrit_1      |         ... 12 more
gerrit_1      | Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:
gerrit_1      |
gerrit_1      | 1) Cannot create ReviewDb
gerrit_1      |   while locating com.google.gerrit.server.schema.ReviewDbDatabaseProvider
gerrit_1      |   while locating com.google.gwtorm.jdbc.Database<com.google.gerrit.reviewdb.server.ReviewDb>
gerrit_1      |   at com.google.gerrit.server.schema.DatabaseModule.configure(DatabaseModule.java:37)
gerrit_1      |   while locating com.google.gwtorm.server.SchemaFactory<com.google.gerrit.reviewdb.server.ReviewDb> annotated with @com.google.gerrit.server.schema.ReviewDbFactory()
gerrit_1      |     for the 1st parameter of com.google.gerrit.server.schema.NotesMigrationSchemaFactory.<init>(NotesMigrationSchemaFactory.java:32)
gerrit_1      |   at com.google.gerrit.server.schema.NotesMigrationSchemaFactory.class(NotesMigrationSchemaFactory.java:25)
gerrit_1      |   while locating com.google.gerrit.server.schema.NotesMigrationSchemaFactory
gerrit_1      |   while locating com.google.gwtorm.server.SchemaFactory<com.google.gerrit.reviewdb.server.ReviewDb>
gerrit_1      | Caused by: com.google.gwtorm.server.OrmException: Unable to determine SqlDialect
gerrit_1      |         at com.google.gwtorm.jdbc.Database.<init>(Database.java:81)
gerrit_1      |         at com.google.gerrit.server.schema.ReviewDbDatabaseProvider.get(ReviewDbDatabaseProvider.java:38)
gerrit_1      |         at com.google.gerrit.server.schema.ReviewDbDatabaseProvider.get(ReviewDbDatabaseProvider.java:27)
gerrit_1      |         at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
gerrit_1      |         at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
gerrit_1      |         at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
gerrit_1      |         at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
gerrit_1      |         at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
gerrit_1      |         at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
gerrit_1      |         at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
gerrit_1      |         at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
gerrit_1      |         at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
gerrit_1      |         at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
gerrit_1      |         at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
gerrit_1      |         at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
gerrit_1      |         at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
gerrit_1      |         at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
gerrit_1      |         at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
gerrit_1      |         at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
gerrit_1      |         at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
gerrit_1      |         at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
gerrit_1      |         at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
gerrit_1      |         at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
gerrit_1      |         at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
gerrit_1      |         at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
gerrit_1      |         at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
gerrit_1      |         at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
gerrit_1      |         at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
gerrit_1      |         at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
gerrit_1      |         at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
gerrit_1      |         at com.google.inject.Guice.createInjector(Guice.java:99)
gerrit_1      |         at com.google.gerrit.pgm.util.SiteProgram.createDbInjector(SiteProgram.java:187)
gerrit_1      |         at com.google.gerrit.pgm.Daemon.start(Daemon.java:325)
gerrit_1      |         at com.google.gerrit.pgm.Daemon.run(Daemon.java:256)
gerrit_1      |         at com.google.gerrit.pgm.util.AbstractProgram.main(AbstractProgram.java:61)
gerrit_1      |         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
gerrit_1      |         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
gerrit_1      |         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
gerrit_1      |         at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by mbhagavathula** [comment]
I resolved this issue by setting the password in the gerrit.config
