### ISSUE TITLE
SSH Key not found

### ISSUE THREAD

**Issue by mbhagavathula** [GerritCodeReview/docker-gerrit#11]
gerrit_1      | 1) No SSH keys under /var/gerrit/etc
gerrit_1      |   while locating com.google.gerrit.sshd.HostKeyProvider
gerrit_1      |   at com.google.gerrit.sshd.SshHostKeyModule.configure(SshHostKeyModule.java:25)
gerrit_1      |   while locating org.apache.sshd.common.keyprovider.KeyPairProvider
gerrit_1      |     for the 6th parameter of com.google.gerrit.sshd.DatabasePubKeyAuth.<init>(DatabasePubKeyAuth.java:72)
gerrit_1      |   while locating com.google.gerrit.sshd.DatabasePubKeyAuth
gerrit_1      |     for the 1st parameter of com.google.gerrit.sshd.CachingPublicKeyAuthenticator.<init>(CachingPublicKeyAuthenticator.java:26)
gerrit_1      |   at com.google.gerrit.sshd.CachingPublicKeyAuthenticator.class(CachingPublicKeyAuthenticator.java:26)
gerrit_1      |   while locating com.google.gerrit.sshd.CachingPublicKeyAuthenticator

**Comment by mbhagavathula** [comment]
Fixed it by uncommenting the entry script
