### ISSUE TITLE
docker-compose for production doesn't work(step 2 )

### ISSUE THREAD

**Issue by ttsrg** [GerritCodeReview/docker-gerrit#19]
Hello.
I beg my pardon, but docker-compose for production doesn't work(step 2 ), with errors:
gerrit_1      | fatal: Cannot make directory /var/gerrit/etc/mail

Attaching to serg_gerrit_1
gerrit_1      | Exception in thread "main" java.io.IOException: Permission denied
gerrit_1      | 	at java.io.UnixFileSystem.createFileExclusively(Native Method)
gerrit_1      | 	at java.io.File.createNewFile(File.java:1012)
gerrit_1      | 	at org.eclipse.jgit.util.FS_POSIX.createNewFileAtomic(FS_POSIX.java:446)
gerrit_1      | 	at org.eclipse.jgit.internal.storage.file.LockFile.lock(LockFile.java:164)
gerrit_1      | 	at org.eclipse.jgit.storage.file.FileBasedConfig.save(FileBasedConfig.java:234)
gerrit_1      | 	at com.google.gerrit.server.index.GerritIndexStatus.save(GerritIndexStatus.java:48)
gerrit_1      | 	at com.google.gerrit.server.index.IndexUtils.setReady(IndexUtils.java:60)
gerrit_1      | 	at com.google.gerrit.pgm.init.InitIndex.run(InitIndex.java:71)
gerrit_1      | 	at com.google.gerrit.pgm.init.SitePathInitializer.run(SitePathInitializer.java:93)
gerrit_1      | 	at com.google.gerrit.pgm.init.BaseInit.run(BaseInit.java:136)
gerrit_1      | 	at com.google.gerrit.pgm.util.AbstractProgram.main(AbstractProgram.java:61)
gerrit_1      | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
gerrit_1      | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
gerrit_1      | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
gerrit_1      | 	at java.lang.reflect.Method.invoke(Method.java:498)
gerrit_1      | 	at com.google.gerrit.launcher.GerritLauncher.invokeProgram(GerritLauncher.java:226)
gerrit_1      | 	at com.google.gerrit.launcher.GerritLauncher.mainImpl(GerritLauncher.java:122)
gerrit_1      | 	at com.google.gerrit.launcher.GerritLauncher.main(GerritLauncher.java:66)
gerrit_1      | 	at Main.main(Main.java:28)
serg_gerrit_1 exited with code 1

**Comment by evenflows** [comment]
you probably already discovered this, but you can create the directory from outside the container,
if that doesnt help, from outside the container chown -R 1000:1000 /directory_where/var/gerrit/etc/mail

1000 is the uid of gerrit inside the container.
