### ISSUE TITLE
Driver class com.mysql.jdbc.Driver not available

### ISSUE THREAD

**Issue by felixlu** [GerritCodeReview/docker-gerrit#5]
Hi all,

We have a MySQL running on another server, so I changed the example config as follows:

etc/gerrit.config

```
...

[database]
  type = mysql
  hostname = 10.0.10.254
  database = gerrit
  username = gerrit

...
```

When I uncommented the `init` entrypoint line in `docker-compose.yaml`, the MySQL connector was downloaded:

```
Recreating gerrit_gerrit_1
Attaching to gerrit_gerrit_1
gerrit_1  | Downloading https://repo1.maven.org/maven2/mysql/mysql-connector-java/5.1.43/mysql-connector-java-5.1.43.jar ... OK
gerrit_1  | Checksum mysql-connector-java-5.1.43.jar OK
gerrit_1  | Generating SSH host key ... rsa... dsa... ed25519... ecdsa 256... ecdsa 384... ecdsa 521... done
gerrit_1  | Initialized /var/gerrit
gerrit_gerrit_1 exited with code 0
```

However, when I commented the `init` again, the container was recreated and **the driver was not downloaded again**:

```
Recreating gerrit_gerrit_1
Attaching to gerrit_gerrit_1
gerrit_1  | Running Gerrit Code Review:
gerrit_1  | [2018-04-03 11:11:30,087] [main] ERROR com.google.gerrit.pgm.Daemon : Unable to start daemon
gerrit_1  | com.google.gerrit.common.Die: Cannot connect to SQL database
gerrit_1  | 	at com.google.gerrit.pgm.util.AbstractProgram.die(AbstractProgram.java:84)
gerrit_1  | 	at com.google.gerrit.pgm.util.SiteProgram.createDbInjector(SiteProgram.java:194)
gerrit_1  | 	at com.google.gerrit.pgm.Daemon.start(Daemon.java:325)
gerrit_1  | 	at com.google.gerrit.pgm.Daemon.run(Daemon.java:256)
gerrit_1  | 	at com.google.gerrit.pgm.util.AbstractProgram.main(AbstractProgram.java:61)
gerrit_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
gerrit_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
gerrit_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
gerrit_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
gerrit_1  | 	at com.google.gerrit.launcher.GerritLauncher.invokeProgram(GerritLauncher.java:223)
gerrit_1  | 	at com.google.gerrit.launcher.GerritLauncher.mainImpl(GerritLauncher.java:119)
gerrit_1  | 	at com.google.gerrit.launcher.GerritLauncher.main(GerritLauncher.java:63)
gerrit_1  | 	at Main.main(Main.java:24)
gerrit_1  | Caused by: java.sql.SQLException: Driver class com.mysql.jdbc.Driver not available
gerrit_1  | 	at com.google.gwtorm.jdbc.SimpleDataSource.loadDriver(SimpleDataSource.java:171)
gerrit_1  | 	at com.google.gwtorm.jdbc.SimpleDataSource.<init>(SimpleDataSource.java:85)
gerrit_1  | 	at com.google.gerrit.server.schema.DataSourceProvider.open(DataSourceProvider.java:161)
gerrit_1  | 	at com.google.gerrit.server.schema.DataSourceProvider.get(DataSourceProvider.java:71)
gerrit_1  | 	at com.google.gerrit.pgm.util.SiteLibraryBasedDataSourceProvider.get(SiteLibraryBasedDataSourceProvider.java:54)
gerrit_1  | 	at com.google.gerrit.pgm.util.SiteLibraryBasedDataSourceProvider.get(SiteLibraryBasedDataSourceProvider.java:31)
gerrit_1  | 	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
gerrit_1  | 	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
gerrit_1  | 	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
gerrit_1  | 	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
gerrit_1  | 	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
gerrit_1  | 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
gerrit_1  | 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
gerrit_1  | 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
gerrit_1  | 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
gerrit_1  | 	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
gerrit_1  | 	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
gerrit_1  | 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
gerrit_1  | 	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
gerrit_1  | 	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
gerrit_1  | 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
gerrit_1  | 	at com.google.inject.Guice.createInjector(Guice.java:99)
gerrit_1  | 	at com.google.gerrit.pgm.util.SiteProgram.createDbInjector(SiteProgram.java:188)
gerrit_1  | 	... 11 more
gerrit_1  | Caused by: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
gerrit_1  | 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
gerrit_1  | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
gerrit_1  | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
gerrit_1  | 	at java.lang.Class.forName0(Native Method)
gerrit_1  | 	at java.lang.Class.forName(Class.java:348)
gerrit_1  | 	at com.google.gwtorm.jdbc.SimpleDataSource.loadDriver(SimpleDataSource.java:168)
gerrit_1  | 	... 33 more
gerrit_gerrit_1 exited with code 1
```

The MySQL driver was downloaded to `/var/gerrit/lib`, however it's not exposed as a volume. 

So how can I put MySQL driver into the container if I want to use MySQL with this docker image? 
Thank you very much!

**Comment by lucamilanesio** [comment]
Hi @felixlu this is simply a public mirror of the [Gerrit Docker main project](https://gerrit-review.googlesource.com/admin/repos/q/filter:docker-gerrit). Can you please post your questions to the [Gerrit Mailing List](https://groups.google.com/forum/#!forum/repo-discuss) and the issues to the [Gerrit Issue Tracker](https://www.gerritcodereview.com/issues.md) ? Thank you.

**Comment by felixlu** [comment]
Sorry @lucamilanesio , actual I tried mounting the folder `lib` as volume and seems it worked. Thank you.
